version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
    healthcheck:
      test: ['CMD-SHELL', 'curl --insecure -sS http://localhost:80 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
